<?php
/**
 * @OA\Tag(
 *     name="account",
 *     description="",
 * )
 * @OA\Tag(
 *     name="users",
 *     description="",
 * )
 * @OA\Tag(
 *     name="stores",
 *     description="",
 * )
 * @OA\Tag(
 *     name="brands",
 *     description="",
 * )
 * @OA\Tag(
 *     name="categories",
 *     description="",
 * )
 * @OA\Tag(
 *     name="collections",
 *     description="",
 * )
 * @OA\Tag(
 *     name="products",
 *     description="",
 * )
 * @OA\Tag(
 *     name="reviews",
 *     description="",
 * )
 * @OA\Tag(
 *     name="addresses",
 *     description="",
 * )
 * @OA\Tag(
 *     name="favorites",
 *     description="",
 * )
 * @OA\Tag(
 *     name="orders",
 *     description="",
 * )
 */
